namespace ThicknessMeasure {
	partial class WaveDisplay {
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose( bool disposing ) {
			if ( disposing && (components != null) ) {
				components.Dispose();
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent() {
			this.components = new System.ComponentModel.Container();
			this.plot = new NPlot.Windows.PlotSurface2D();
			this.timer1 = new System.Windows.Forms.Timer(this.components);
			this.bClear = new System.Windows.Forms.Button();
			this.SuspendLayout();
			// 
			// plot
			// 
			this.plot.AutoScaleAutoGeneratedAxes = false;
			this.plot.AutoScaleTitle = false;
			this.plot.BackColor = System.Drawing.SystemColors.ControlLightLight;
			this.plot.DateTimeToolTip = false;
			this.plot.Legend = null;
			this.plot.LegendZOrder = -1;
			this.plot.Location = new System.Drawing.Point(12, 47);
			this.plot.Name = "plot";
			this.plot.RightMenu = null;
			this.plot.ShowCoordinates = false;
			this.plot.Size = new System.Drawing.Size(586, 354);
			this.plot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighSpeed;
			this.plot.TabIndex = 0;
			this.plot.Text = "plotSurface2D1";
			this.plot.Title = "";
			this.plot.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
			this.plot.XAxis1 = null;
			this.plot.XAxis2 = null;
			this.plot.YAxis1 = null;
			this.plot.YAxis2 = null;
			// 
			// timer1
			// 
			this.timer1.Interval = 300;
			this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
			// 
			// bClear
			// 
			this.bClear.Location = new System.Drawing.Point(314, 15);
			this.bClear.Name = "bClear";
			this.bClear.Size = new System.Drawing.Size(79, 20);
			this.bClear.TabIndex = 1;
			this.bClear.Text = "Clear";
			this.bClear.UseVisualStyleBackColor = true;
			this.bClear.Click += new System.EventHandler(this.bClear_Click);
			// 
			// WaveDisplay
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(800, 450);
			this.Controls.Add(this.bClear);
			this.Controls.Add(this.plot);
			this.Name = "WaveDisplay";
			this.Text = "WaveDisplay";
			this.Load += new System.EventHandler(this.WaveDisplay_Load);
			this.ResizeEnd += new System.EventHandler(this.WaveDisplay_ResizeEnd);
			this.ResumeLayout(false);

		}

		#endregion

		private NPlot.Windows.PlotSurface2D plot;
		private System.Windows.Forms.Timer timer1;
		private System.Windows.Forms.Button bClear;
	}
}